CREATE DATABASE pulsar;

CREATE TABLE IF NOT EXISTS ORDERS(
    ID SERIAL NOT NULL,
    ORDER_ID INT NOT NULL PRIMARY KEY,
    ACCT_NUMBER VARCHAR(10) NOT NULL,
    SYMBOL VARCHAR(5) NOT NULL,
    QUANTITY INT NOT NULL,
    SIDE VARCHAR(5) NOT NULL,
    LIMIT_PRICE FLOAT NOT NULL,
    STOP_PRICE FLOAT NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO ORDERS(ORDER_ID, ACCT_NUMBER, SYMBOL, QUANTITY, SIDE, LIMIT_PRICE, STOP_PRICE) VALUES(1000, 'TOKYO001', 'AAPL', 100, 'buy', 104.29, 105.90);